# Generated by Django 5.0.1 on 2024-01-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_table_alter_reservation_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='finish_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_time',
        ),
    ]
