# Generated by Django 5.0.1 on 2024-01-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_rename_finish_time_reservation_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]
