# Generated by Django 5.0.1 on 2024-01-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_restaurant_address_restaurant_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
